class RetryableException(Exception):
    pass


class ClientError(Exception):
    pass
